#!/bin/sh

export SDL_VIDEODRIVER=wayland
export _JAVA_AWT_WM_NONREPARENTING=1
export QT_QPA_PLATFORM=xcb
export XDG_CURRENT_DESKTOP=sway
export XDG_SESSION_DESKTOP=sway

exec /usr/bin/sway --config $HOME/.config/sway/config "$@"
